# Generated by Django 5.1.1 on 2024-09-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('telpon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_transaksi', models.CharField(choices=[('Pengeluaran', 'Pengeluaran'), ('Pemasukan', 'Pemasukan')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.anggota')),
            ],
        ),
    ]
